<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Attendance Report</title>
    <style>
        @page { margin: 0px; }
        body { font-family: 'Helvetica', sans-serif; margin: 30px; color: #334155; }
        
        .header-bg {
            position: absolute; top: 0; left: 0; right: 0; height: 120px;
            background-color: #f8fafc; border-bottom: 2px solid #e2e8f0; z-index: -1;
        }
        
        .header { margin-bottom: 40px; padding-top: 20px; }
        .logo { font-size: 28px; font-weight: 900; color: #0f172a; letter-spacing: -1px; }
        .logo span { color: #4f46e5; }
        
        .report-info { float: right; text-align: right; }
        .report-title { font-size: 18px; font-weight: bold; color: #0f172a; text-transform: uppercase; letter-spacing: 1px; }
        .report-meta { font-size: 12px; color: #64748b; margin-top: 4px; }

        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { 
            background-color: #0f172a; color: #ffffff; 
            font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px;
            padding: 12px 10px; text-align: left;
        }
        td { 
            padding: 12px 10px; border-bottom: 1px solid #e2e8f0; 
            font-size: 11px; vertical-align: middle;
        }
        tr:nth-child(even) { background-color: #f8fafc; }
        
        .emp-name { font-weight: bold; color: #0f172a; display: block; font-size: 12px; }
        .emp-role { font-size: 9px; color: #64748b; text-transform: uppercase; margin-top: 2px; }
        
        .status { 
            font-size: 9px; font-weight: bold; text-transform: uppercase; 
            padding: 4px 8px; border-radius: 4px; display: inline-block;
        }
        .status-late { background-color: #fef2f2; color: #ef4444; border: 1px solid #fee2e2; }
        .status-present { background-color: #ecfdf5; color: #10b981; border: 1px solid #d1fae5; }

        .footer { 
            position: fixed; bottom: 30px; left: 30px; right: 30px; 
            border-top: 1px solid #e2e8f0; padding-top: 10px;
            font-size: 10px; color: #94a3b8; text-align: center;
        }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>
    <div class="header-bg"></div>
    
    <div class="header">
        <div style="float: left;">
            <div class="logo">POS<span>SYSTEM</span></div>
            <div style="font-size: 12px; color: #64748b; margin-top: 5px;">HR Department</div>
        </div>
        <div class="report-info">
            <div class="report-title">{{ $title }}</div>
            <div class="report-meta">{{ $dateInfo }}</div>
            <div class="report-meta">Generated: {{ now()->format('M d, Y h:i A') }}</div>
        </div>
        <div style="clear: both;"></div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="30%">Employee Details</th>
                <th width="20%">Date</th>
                <th width="15%">Clock In</th>
                <th width="15%">Clock Out</th>
                <th width="20%" style="text-align: right;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $record)
            <tr>
                <td>
                    <span class="emp-name">{{ $record->user->name }}</span>
                    <span class="emp-role">{{ $record->user->role }}</span>
                </td>
                <td style="color: #475569;">{{ \Carbon\Carbon::parse($record->date)->format('M d, Y') }}</td>
                <td style="color: #0f172a; font-weight: bold; font-family: monospace;">{{ \Carbon\Carbon::parse($record->check_in)->format('h:i A') }}</td>
                <td style="color: #64748b; font-family: monospace;">{{ $record->check_out ? \Carbon\Carbon::parse($record->check_out)->format('h:i A') : '--:--' }}</td>
                <td style="text-align: right;">
                    <span class="status {{ $record->status === 'Late' ? 'status-late' : 'status-present' }}">
                        {{ $record->status }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Confidential Document &bull; Generated by POS System &bull; Page <span class="page-number"></span>
    </div>
</body>
</html> 